pipeline:
  name: OSM Next.js CI Pipeline
  identifier: osm_nextjs_ci_pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: account.github
        repoName: ayointegral/osm-nextjs
        build: <+input>
  stages:
    - stage:
        name: Build and Deploy OSM Next.js
        identifier: build_deploy_osm_nextjs
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: dockerdelegate
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  name: Setup and Run
                  identifier: setup_and_run
                  type: Run
                  spec:
                    connectorRef: account.dockerhub
                    image: node:18
                    shell: Bash
                    command: |
                      echo "Installing dependencies"
                      apt-get update
                      apt-get install -y git docker.io docker-compose

                      echo "Installing Node.js dependencies"
                      npm install

                      echo "Building Next.js application"
                      npm run build

                      echo "Running tests"
                      npm run test
